[#16] 타입스크립트 프로젝트로 변환
GyeongSoTone/danplay-frontend pull request #19
Opened 2022-09-09 08:47 UTC by park-daeun

[#16]

## 👩🏻‍💻 작업 내용

- 자바스크립트 프로젝트를 타입스크립트로 변환합니다.

## 📝 PR 포인트

- 

## ➕ 기타

-

2022-09-09 13:06 UTC, Yunkeun requested changes
위에 Participants에 대해서 내용만 보완해주시고 host에 대해서는 논의가 필요할 것 같습니다.

2022-09-09 13:06 UTC, Yunkeun commented on src/models/match/Participants.ts
> +  age: number
성별도 들어가야할 것 같습니다.

host에 대해서, 궁금한 점이
한 유저는 여러개의 경기에 host가 될 수 있을텐데, 이러한 경우 경기마다 새로운 Participants 객체(타입?)를 생성해야하는 비효율이 생깁니다.
해결 방법이 뭐가 있을까요?

2022-09-09 13:39 UTC, Yunkeun commented on src/models/match/Participants.ts
> +  age: number
백엔드 측 구현내용 보니 hostId로 host 유저를 Match에 저장했네요

2022-09-12 09:36 UTC, park-daeun commented on src/models/match/Participants.ts
> +  age: number
> 백엔드 측 구현내용 보니 hostId로 host 유저를 Match에 저장했네요

오옹 좋네요 👍
일단 지금 목데이터는 마크업 구현을 위해 제 맘대로 만들었던 것 같은데요,,
예전 파일을 타입스크립트로 바꾸다보니 현재 백엔드 쪽은 고려안한 채 일단 바꾸었어요!!
세부 기능 각각 구현하면서 바꿔보도록 할게욥!! 
그 과정에서 논의 필요한 데이터 타입이나 추가로 필요한 응답 필드 등은 그때그때 연락드리도록 하겠습니당!

2022-09-12 13:28 UTC, Yunkeun commented on src/models/match/Participants.ts
> +  age: number
좋습니당 일단 resolve conversation 할게요!

2022-09-13 10:37 UTC, Yunkeun approved these changes

2022-09-13 10:38 UTC, merged